### ISSUE TITLE
Ternary weights not reflected in caffe model

### ISSUE THREAD

**Issue by sunejas** [dongyp13/Stochastic-Quantization#2]
Hi @dongyp13,
Thank you for sharing the code.
I am training the ImageNet/AlexNet-BN/SQ-TWN from scratch. The network seems to be learning, 50K iterations of the first stage have run so far, and I can see the Top1/Top5 accuracy as 0.12/0.28. 
I extracted the trained weights from this caffemodel snapshot, and was expecting that 50% (= r) of the weight values would be +1/0/-1, but I dont see such quantized weights for any conv/fc layer in the caffe model.
Could you please guide from where to obtain the quantized weights? Is there any special way to dump them, or will they get reflected in the caffe model after all the stages have run?

**Comment by dongyp13** [comment]
Yes, the weights in caffemodel files are still full-precision. We actually save the full-precision weights instead of low-bits weights. 
The accuracy results in the first stage are sometimes useless. Only the models after the forth(final) stage can obtain good results. 
If you look at our codes, you will find that we first quantize the full-precision weights to low-bit weights and then perform forward propagation, even at the testing stage. So if you want to get the quantized weights for further usage, you probably need to quantize the weights and save them manually.

**Comment by sunejas** [comment]
Thanks for the clarification, I was able to obtain the quantized weights.

**Comment by mychina75** [comment]
Hi, @sunejas 
How can you obtain the quantized weights, can you provide the script?
Thank you.
